/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Project Euler
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms. 
 *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */


#include <stdio.h>
#include <stdlib.h>

int main(void)
{	/* declare initial variables */
	int sum;
	int num1 = 0;
	int num2 = 1;
	int even_sum = 0;
	/* get fibonacci sequence terms*/
	do
	{
		sum = num1 + num2; 
		num1 = num2; 	 
		num2 = sum;		
		/* add even fibonacci sequence terms */
		if (sum % 2 == 0)
		{
			even_sum += sum;
		}
	}
	while (sum < 4000000);
	printf("%d\n", even_sum);
}
	
